#!/usr/bin/env node
/**
 * Extracts the inner geometry of a curated set of Lucide icons into a TS module,
 * so only the icons actually in the vocabulary ship to the browser.
 *
 * Add a name to src/lib/icon-names.json, re-run, commit the generated file.
 *
 * Usage: node scripts/gen-icons.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const NAMES = JSON.parse(await readFile('src/lib/icon-names.json', 'utf8'));
const OUT = 'src/lib/icons.generated.ts';

const missing = [];
const entries = [];

for (const name of [...NAMES].sort()) {
  const path = `node_modules/lucide-static/icons/${name}.svg`;
  if (!existsSync(path)) {
    missing.push(name);
    continue;
  }
  const svg = await readFile(path, 'utf8');
  // Keep only the geometry; stroke/size come from the call site.
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!inner) {
    missing.push(name);
    continue;
  }
  entries.push([name, inner]);
}

if (missing.length) {
  console.error(`Not found in lucide-static: ${missing.join(', ')}`);
  process.exit(1);
}

const body = entries
  .map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`)
  .join('\n');

await writeFile(
  OUT,
  `// GENERATED by scripts/gen-icons.mjs — do not edit.
// Source: lucide-static (ISC). Geometry only; stroke and size are set by the caller.
// All icons use a 24x24 viewBox.

export const ICON_VIEWBOX = 24;

export const ICONS: Record<string, string> = {
${body}
};

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS);
`,
);

console.log(`wrote ${OUT} — ${entries.length} icons`);
